export const ALL_BORROWS_REQUEST = "ALL_BORROWS_REQUEST";
export const ALL_BORROWS_SUCCESS = "ALL_BORROWS_SUCCESS";
export const ALL_BORROWS_FAIL = "ALL_BORROWS_FAIL";
export const BORROW_DETAILS_REQUEST = "BORROW_DETAILS_REQUEST";
export const BORROW_DETAILS_SUCCESS = "BORROW_DETAILS_SUCCESS";
export const BORROW_DETAILS_FAIL = "BORROW_DETAILS_FAIL";
export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";

export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";

export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const ADMIN_BORROWS_REQUEST = "ADMIN_BORROWS_REQUEST";

export const ADMIN_BORROWS_SUCCESS = "ADMIN_BORROWS_SUCCESS";

export const ADMIN_BORROWS_FAIL = "ADMIN_BORROWS_FAIL";
export const NEW_BORROW_REQUEST = "NEW_BORROW_REQUEST";

export const NEW_BORROW_SUCCESS = "NEW_BORROW_SUCCESS";

export const NEW_BORROW_RESET = "NEW_BORROW_RESET";

export const NEW_BORROW_FAIL = "NEW_BORROW_FAIL";
export const DELETE_BORROW_REQUEST = "DELETE_BORROW_REQUEST";

export const DELETE_BORROW_SUCCESS = "DELETE_BORROW_SUCCESS";

export const DELETE_BORROW_RESET = "DELETE_BORROW_RESET";

export const DELETE_BORROW_FAIL = "DELETE_BORROW_FAIL";
export const UPDATE_BORROW_REQUEST = "UPDATE_BORROW_REQUEST";

export const UPDATE_BORROW_SUCCESS = "UPDATE_BORROW_SUCCESS";

export const UPDATE_BORROW_RESET = "UPDATE_BORROW_RESET";

export const UPDATE_BORROW_FAIL = "UPDATE_BORROW_FAIL";
export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";

export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";

export const GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";

export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";

export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
